-- MULTIPLE COLUMN PRIMARY KEYS
ALTER TABLE Stock
ALTER PRODUCT_ID INTEGER NOT NULL;
ALTER TABLE Stock
ALTER LOCATION_ID INTEGER NOT NULL;
ALTER TABLE Stock
ADD CONSTRAINT PK_STOCK PRIMARY KEY (PRODUCT_ID, LOCATION_ID);

ALTER TABLE ORDERDETAIL
ALTER ORDER_ID INTEGER NOT NULL;
ALTER TABLE ORDERDETAIL
ALTER PRODUCT_ID INTEGER NOT NULL;
ALTER TABLE ORDERDETAIL
ADD CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDER_ID, PRODUCT_ID);

    -- NOT NULL CONSTRAINTS
-- PRODUCT
ALTER TABLE PRODUCT
ALTER CATEGORY_ID integer NOT NULL;

ALTER TABLE PRODUCT
ALTER SUPPLIER_ID integer NOT NULL;

-- ORDERDETAIL
ALTER TABLE ORDERDETAIL
ALTER PRODUCT_ID integer NOT NULL;

ALTER TABLE ORDERDETAIL
ALTER ORDER_ID integer NOT NULL;

-- STOCK
ALTER TABLE Stock
ALTER PRODUCT_ID INTEGER NOT NULL;

ALTER TABLE Stock
ALTER LOCATION_ID INTEGER NOT NULL;

-- ORDER (CUSTOMER_ORDER)
ALTER TABLE CUSTOMER_ORDER
ALTER SHIPPEDFROM_ID INTEGER NOT NULL;

ALTER TABLE CUSTOMER_ORDER
ALTER CUSTOMER_ID INTEGER NOT NULL;

-- REVENUE
ALTER TABLE REVENUE
ALTER LOCATION_ID INTEGER NOT NULL;