-- FK CONSTRAINTS PRODUCT
ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_PRODUCTCATEGORY
        FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(ID);

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_SUPPLIER
        FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID);

-- FK ORDER DETAIL
ALTER TABLE ORDERDETAIL
    ADD CONSTRAINT FK_ORDERDETAIL_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);

ALTER TABLE ORDERDETAIL
    ADD CONSTRAINT FK_ORDERDETAIL_ORDER
        FOREIGN KEY (ORDER_ID) REFERENCES CUSTOMER_ORDER(ID);

-- FK ORDER STOCK
ALTER TABLE Stock
    ADD CONSTRAINT FK_Product_Stock
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);

ALTER TABLE Stock
    ADD CONSTRAINT FK_Location_Stock
        FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID);

-- FK ORDER (CUSTOMER_ORDER)
ALTER TABLE CUSTOMER_ORDER
    ADD CONSTRAINT FK_CUSTOMERORDER_LOCATION
        FOREIGN KEY (SHIPPEDFROM_ID) REFERENCES LOCATION(ID);

ALTER TABLE CUSTOMER_ORDER
    ADD CONSTRAINT FK_CUSTOMERORDER_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);

-- REVENUE FK
ALTER TABLE REVENUE
    ADD CONSTRAINT FK_REVENUE_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID);