INSERT INTO LOCATION(ID, NAME, COUNTRY, CITY, COUNTY, STREET_ADDRESS)
VALUES(201, 'London Store', 'UK', 'London', 'London', 'Oxford Street 22nd');
    INSERT INTO LOCATION(ID, NAME, COUNTRY, CITY, COUNTY, STREET_ADDRESS)
VALUES(202, 'Nottingham Store', 'UK', 'Nottingham', 'Nottinghamshire', 'Coal Street 18th');

INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES(101, 201, 60);
INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES(102, 201, 50);
INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES(101, 202, 40);

INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL_ADDRESS)
VALUES(401, 'John', 'Stone', 'jstone', 'chicken', 'j_stone@kfc.com');
INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL_ADDRESS)
VALUES(402, 'Nicole', 'Brown', 'nbrown', 'candy', 'n_brown@milka.com');