INSERT INTO PRODUCT_CATEGORY(ID, NAME, DESCRIPTION)
VALUES(1, 'T-Shirts', 'Tshirt description');
INSERT INTO PRODUCT_CATEGORY(ID, NAME, DESCRIPTION)
VALUES(2, 'Pants', 'Pants description');

INSERT INTO SUPPLIER(ID, NAME)
VALUES(11, 'Adidas');
INSERT INTO SUPPLIER(ID, NAME)
VALUES(12, 'Puma');

INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE, WEIGHT, CATEGORY_ID, SUPPLIER_ID, IMAGE_URL)
VALUES(101, 'Adidas Jogging Pants', 'Pants to wear while jogging', 30.00, 1, 2, 11, 'google.com/pantsimage');
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE, WEIGHT, CATEGORY_ID, SUPPLIER_ID, IMAGE_URL)
VALUES(102, 'Puma T-shirt', 'Casual t-shirt', 25.00, 1, 1, 12, 'google.com/thisrtimage');