INSERT INTO CUSTOMER_ORDER(ID, SHIPPEDFROM_ID, CUSTOMER_ID, CREATED_AT, COUNTRY, CITY, COUNTY, STREET_ADDRESS)
VALUES(501, 201, 401, CURRENT_TIMESTAMP(), 'France', 'Tours', 'Paris MA', 'FrenchStreet 7');
    INSERT INTO CUSTOMER_ORDER(ID, SHIPPEDFROM_ID, CUSTOMER_ID, CREATED_AT, COUNTRY, CITY, COUNTY, STREET_ADDRESS)
VALUES(502, 202, 402, CURRENT_TIMESTAMP(), 'UK', 'Manchester', 'Manchester MA', 'Victory Road 21st');

INSERT INTO REVENUE(ID, LOCATION_ID, DATE, SUM)
VALUES(51, 201, CURRENT_TIMESTAMP, 700);

INSERT INTO ORDERDETAIL(ORDER_ID, PRODUCT_ID, QUANTITY)
VALUES(501, 101, 4);
INSERT INTO ORDERDETAIL(ORDER_ID, PRODUCT_ID, QUANTITY)
VALUES(501, 102, 3);
INSERT INTO ORDERDETAIL(ORDER_ID, PRODUCT_ID, QUANTITY)
VALUES(502, 101, 1);